2018-08-07 15:15:46,288 ERROR:Exception on /index [GET] [in C:\Users\huanri\myproject\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\huanri\myproject\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\huanri\myproject\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\huanri\myproject\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huanri\myproject\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\huanri\myproject\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\huanri\myproject\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 25, in index
    return render_template("index.html", title='Home', user=user, posts=posts
  File "C:\Users\huanri\myproject\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\huanri\myproject\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "C:\Users\huanri\myproject\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'form' is undefined
2018-08-07 15:21:35,342 ERROR:Exception on /index [GET] [in C:\Python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 25, in index
    return render_template("index.html", title='Home', user=user, posts=posts
  File "C:\Python36\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Python36\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-08-07 15:23:28,032 ERROR:Exception on /index [GET] [in C:\Python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\huanri\PycharmProjects\myproject\app\views.py", line 25, in index
    return render_template("index.html", title='Home', user=user, posts=posts
  File "C:\Python36\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Python36\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\huanri\PycharmProjects\myproject\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "C:\Python36\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
